const $=id=>document.getElementById(id),fmt=new Intl.NumberFormat('en-US');let data,filtered=[];
const dateTime=value=>new Date(value).toLocaleString(undefined,{hour12:false});
const compact=n=>{if(n>=1e9)return(n/1e9).toFixed(2)+' G';if(n>=1e6)return(n/1e6).toFixed(2)+' M';if(n>=1e3)return(n/1e3).toFixed(2)+' K';return n.toFixed(4)};
const pct=(n,t)=>(t?n*100/t:0).toFixed(1)+'%';
fetch('/api/dashboard').then(r=>r.json()).then(d=>{data=d;filtered=d.blocks;render()}).catch(()=>document.body.innerHTML='<main><h1>Dashboard data unavailable</h1></main>');
function render(){const s=data.statistics,b=data.blocks,latest=b[0]||{Difficulty:0};$('source').textContent=data.source;$('scanTime').textContent=data.scan_seconds.toFixed(2)+' sec';$('generated').textContent=dateTime(data.generated_at);$('explorer').href=data.explorer_url;$('footerVersion').textContent=`CHTA-NetworkStats v${data.version}`;$('blockCount').textContent=b.length;
 const cardData=[['↗','HEIGHT',fmt.format(data.height),'Current Height',''],['▱','SCANNED BLOCKS',s.TotalBlocks,'Blocks Analyzed',''],['⌁','NETWORK DIFFICULTY',compact(latest.Difficulty),'Current Difficulty',''],['◇','TOTAL BLOCKS',s.TotalBlocks,'In Window',''],['✓','NORMAL BLOCKS',s.NormalBlocks,pct(s.NormalBlocks,s.TotalBlocks),'good'],['⚠','LOW-DIFF BLOCKS',s.LowDiffBlocks,pct(s.LowDiffBlocks,s.TotalBlocks),'warn'],['◷','AVG GAP',s.AverageGap.toFixed(1)+' sec','Average Time Gap','']];
 $('cards').innerHTML=cardData.map(x=>`<div class="card"><span class="icon">${x[0]}</span><label>${x[1]}</label><strong>${x[2]}</strong><small class="${x[4]}">${x[3]}</small></div>`).join('');renderTypes();renderPools();renderStats();renderRows();drawChart()}
function renderTypes(){const s=data.statistics,p=s.TotalBlocks?s.NormalBlocks/s.TotalBlocks*100:0;$('types').innerHTML=`<div class="donut" style="background:conic-gradient(var(--green) 0 ${p}%,var(--orange) ${p}% 100%)"></div><div class="legend"><div><span class="dot" style="background:var(--green)"></span>NORMAL (${s.NormalBlocks})<b>${p.toFixed(1)}%</b></div><div><span class="dot" style="background:var(--orange)"></span>LOW-DIFF (${s.LowDiffBlocks})<b>${(100-p).toFixed(1)}%</b></div></div>`}
function renderPools(){$('pools').innerHTML=data.pools.map(p=>`<div class="bar-item"><span class="bar-label">${esc(p.Name)}</span><div class="track"><div class="fill" style="width:${p.Percent}%"></div></div><b>${p.TotalBlocks} (${p.Percent.toFixed(1)}%)</b></div>`).join('')||'<p>No pool data</p>'}
function renderStats(){const s=data.statistics,b=data.blocks,ds=b.map(x=>x.Difficulty).sort((a,c)=>a-c),avg=ds.reduce((a,c)=>a+c,0)/(ds.length||1),median=ds.length?(ds[Math.floor((ds.length-1)/2)]+ds[Math.ceil((ds.length-1)/2)])/2:0;let runs={NORMAL:0,'LOW-DIFF':0},curType=b[0]?.Type||'—',cur=0,last='',currentCount=0;for(const x of b){if(x.Type===last)cur++;else{last=x.Type;cur=1}runs[x.Type]=Math.max(runs[x.Type]||0,cur)}for(const x of b){if(x.Type===curType)currentCount++;else break}const oldest=b[b.length-1],newest=b[0];
 $('networkStats').innerHTML=rows([['Total Blocks',s.TotalBlocks],['Normal Blocks',`${s.NormalBlocks} (${pct(s.NormalBlocks,s.TotalBlocks)})`],['LOW-DIFF Blocks',`${s.LowDiffBlocks} (${pct(s.LowDiffBlocks,s.TotalBlocks)})`],['Average Gap',s.AverageGap.toFixed(1)+' sec'],['Minimum Gap',s.MinGap+' sec'],['Maximum Gap',s.MaxGap+' sec'],['Scan Time',data.scan_seconds.toFixed(2)+' sec'],['Data Source',data.source,'good']]);
 $('difficultyStats').innerHTML=rows([['Minimum Difficulty',compact(ds[0]||0)],['Maximum Difficulty',compact(ds[ds.length-1]||0)],['Average Difficulty',compact(avg)],['Median Difficulty',compact(median)]]);
 $('streakStats').innerHTML=rows([['Current Streak',`${curType} (${currentCount})`,curType==='LOW-DIFF'?'warn':'good'],['Longest LOW-DIFF',runs['LOW-DIFF']],['Longest NORMAL',runs.NORMAL]]);
 $('timeStats').innerHTML=rows([['From (Height)',oldest?fmt.format(oldest.Height):'—'],['To (Height)',newest?fmt.format(newest.Height):'—'],['From (Time)',oldest?dateTime(oldest.Time):'—'],['To (Time)',newest?dateTime(newest.Time):'—']])}
function rows(v){return v.map(x=>`<div class="stat-row"><span>${x[0]}</span><b class="${x[2]||''}">${x[1]}</b></div>`).join('')}
function renderRows(){$('blockRows').innerHTML=filtered.map(b=>`<tr><td>${fmt.format(b.Height)}</td><td>${dateTime(b.Time)}</td><td class="pool">${esc(b.Pool)}</td><td>${compact(b.Difficulty)}</td><td><span class="badge ${b.Type.toLowerCase()}">${b.Type}</span></td><td>${b.Gap>0?'+':''}${b.Gap}s</td><td>${b.TxCount}</td><td><a class="out" href="${data.explorer_url}/block/${encodeURIComponent(b.Hash)}" target="_blank" rel="noreferrer">View on Explorer ↗</a></td></tr>`).join('')}
$('filter').addEventListener('input',e=>{let q=e.target.value.toLowerCase();filtered=data.blocks.filter(b=>String(b.Height).includes(q)||b.Hash.toLowerCase().includes(q)||b.Pool.toLowerCase().includes(q));renderRows()});
function drawChart(){const c=$('difficulty'),ctx=c.getContext('2d'),r=c.getBoundingClientRect(),d=devicePixelRatio||1;c.width=r.width*d;c.height=r.height*d;ctx.scale(d,d);const w=r.width,h=r.height,p={l:50,r:12,t:12,b:25},v=[...data.blocks].reverse(),logs=v.map(x=>Math.log10(Math.max(x.Difficulty,.0001))),min=Math.floor(Math.min(...logs)),max=Math.ceil(Math.max(...logs)),x=i=>p.l+i*(w-p.l-p.r)/Math.max(v.length-1,1),y=n=>p.t+(max-n)*(h-p.t-p.b)/Math.max(max-min,1);ctx.font='9px Segoe UI';for(let n=min;n<=max;n++){let yy=y(n);ctx.strokeStyle='#153143';ctx.beginPath();ctx.moveTo(p.l,yy);ctx.lineTo(w-p.r,yy);ctx.stroke();ctx.fillStyle='#91a5b6';ctx.fillText('10^'+n,4,yy+3)}ctx.beginPath();logs.forEach((n,i)=>i?ctx.lineTo(x(i),y(n)):ctx.moveTo(x(i),y(n)));ctx.strokeStyle='#168cff';ctx.lineWidth=1.5;ctx.stroke();logs.forEach((n,i)=>{ctx.beginPath();ctx.arc(x(i),y(n),2,0,Math.PI*2);ctx.fillStyle='#168cff';ctx.fill()})}
addEventListener('resize',()=>data&&drawChart());function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
